# vim:ft=yaml.ansible
---
- name: Install Docker
  become: true
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
    state: latest
  with_items:
    - docker
    - docker-compose
    - docker-buildx
    - lazydocker

- name: Docker Group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: true

- name: Enable docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
