# vim:ft=yaml.ansible
---
- name: Check NVM
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  register: nvm_status

- name: Install NVM and Node
  ansible.builtin.shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/refs/heads/master/install.sh | bash
    source $HOME/.nvm/nvm.sh
    nvm install --lts
    npm install -g pnpm
  when: not nvm_status.stat.exists

