# vim:ft=yaml.ansible
---
- name: Install tmux
  become: true
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
    state: latest
  with_items:
    - tmux

- name: Tmux Config
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: "{{ ansible_env.HOME }}/dotfiles/configs/tmux.conf", dest: "{{ ansible_env.HOME }}/.tmux.conf" }
