[location]
address         = "Tarnowskie Góry, Poland"
refresh_minutes = 30

[plugins]
enabled = [ "noctalia/translator", "noctalia/wallhaven", "noctalia/timer" ]

[shell]
screen_time_enabled = true
time_format = "{:%H:%M:%S}"

[idle.behavior.lock]
timeout = 600
action = "lock"
enabled = true

[lockscreen]
blur_intensity = 0.5
blurred_desktop = true
tint_intensity = 0.7

[theme.templates]
builtin_ids = [ "btop", "ghostty", "hyprland" ]
community_ids = [ "neovim", "yazi" ]

[widget.battery]
enabled = false

[widget.brightness]
enabled = false

[widget.network]
enabled = false

[widget.wallpaper]
enabled = false

[widget.launcher]
enabled = false

[widget.clock]
format = "{:%H:%M:%S}"

[widget.wallhaven]
type = "noctalia/wallhaven:wallhaven"

[theme.templates.user.nvim-base16]
input_path = "~/.config/nvim/lua/matugen-template.lua"
output_path = "~/.config/nvim/lua/matugen.lua"
post_hook = 'pkill -SIGUSR1 nvim'
