---
- name: Include Darwin specific tasks
  ansible.builtin.include_tasks: "./{{ task }}"
  when: ansible_os_family == 'Darwin'
  loop:
    - gaming.darwin.yml
  loop_control:
    loop_var: task

- name: Include Linux specific tasks
  ansible.builtin.include_tasks: "./{{ task }}"
  when: ansible_os_family == 'Linux'
  loop:
    - gaming.arch.yml
  loop_control:
    loop_var: task
