version: "3"

services:
  database:
    image: postgres:17
    container_name: localhost-database
    volumes:
      - ./data/psql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - TZ="Europe/Warsaw"
