# vim: set ft=tmux tw=0 nowrap:
########################################
## PLUGINS ##
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-sensible'

## PLUGIN OPTIONS ##
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'
########################################

########################################
## CORE OPTIONS ##
set-window-option -g mode-keys vi
set -g mouse on
set -g detach-on-destroy off
set -g status-position top

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane
########################################
## KEYBINDS ##
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

bind a choose-tree

unbind %
unbind '"'
unbind s

bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

unbind r
bind r source-file ~/.tmux.conf; display-message "Tmux Config Reloaded!"

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5
bind -r m resize-pane -Z

bind -r p previous-window
bind -r n next-window
bind -r ( switch-client -p
bind -r ) switch-client -n

bind-key e display-popup -T "Tmux Sessionizer" -E tmux-sessionizer
bind-key f display-popup -T "Search tmux all sessions windows" -E tmux-fzf
bind-key g display-popup -T "Search tmux windows in session" -E tmux-fzf --win
bind-key K display-popup -T "Create a new project!" -E keker
bind-key T display-popup -T "Launcher" -E launcher-fzf
########################################

########################################
## STATUS BAR ##
set -g status-interval 1
set-option -g status "on"

set -g status-style "bg=default,fg=default"
set -g status-left-style "bg=default,fg=default"
set -g status-right-style "bg=default,fg=default"
set -g window-status-style "bg=default,fg=default"
set -g window-status-current-style "bg=default,fg=default"
set -g window-status-last-style "bg=default,fg=default"
set -g window-status-activity-style "bg=default,fg=default,underscore"
set -g window-status-bell-style "bg=default,fg=default,bold"

set -g status-left-length 100

set-window-option -g window-status-separator "  "

currentSession="#[fg=default,dim][#S]"
time_text="#[fg=default,dim] %Y-%m-%d %H:%M:%S"
currentFormat="#[fg=default,bold]#I:#W#F"
otherFormat="#[fg=default,dim]#I:#W#F"

set-option -g status-position top
set-option -g status-left " $currentSession "
set-option -g status-right " $time_text "
set-window-option -g window-status-current-format "$currentFormat"
set-window-option -g window-status-format "$otherFormat"
########################################

run '~/.tmux/plugins/tpm/tpm'
