# vim:ft=yaml.ansible
---
# NOTE: For Darwin I am using Raycast to switch between apps,
# so there is no need to use tiling window manager like aerospace or yabai
#
# - name: Darwin | Include Darwin specific tasks
#   ansible.builtin.include_tasks: "./{{ task }}"
#   when: ansible_os_family == 'Darwin'
#   loop:
#     -
#   loop_control:
#     loop_var: task

- name: Arch | Include Linux specific tasks
  ansible.builtin.include_tasks: "./{{ task }}"
  when: ansible_os_family == 'Archlinux'
  loop:
    - hyprland.arch.yml
  loop_control:
    loop_var: task
