# vim:ft=yaml.ansible
---
- name: Darwin | Include Darwin specific tasks
  ansible.builtin.include_tasks: "./{{ task }}"
  when: ansible_os_family == 'Darwin'
  loop:
    - tiling.darwin.yml
  loop_control:
    loop_var: task

- name: Arch | Include Linux specific tasks
  ansible.builtin.include_tasks: "./{{ task }}"
  when: ansible_os_family == 'Archlinux'
  loop:
    - tiling.arch.yml
  loop_control:
    loop_var: task
