# vim:filetype=yaml.ansible
---
- name: Brew tap for tiling stuff
  community.general.homebrew_tap:
    name: "{{ item }}"
  loop:
    - FelixKratz/formulae

- name: Install tiling stuff
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - sketchybar
    - jq
    - raycast
    - nikitabobko/tap/aerospace
    - borders

- name: Check if sketchybar font is available
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/Library/Fonts/sketchybar-app-font.ttf"
  register: found_files

- name: Get font for sketchybar
  ansible.builtin.shell: |
    set -o pipefail
    curl -L https://github.com/kvndrsslr/sketchybar-app-font/releases/download/v2.0.25/sketchybar-app-font.ttf -o $HOME/Library/Fonts/sketchybar-app-font.ttf
  when: not found_files.stat.exists
  changed_when: true

- name: Remove aerospace default config
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.aerospace.toml"
    state: absent

- name: Config tiling
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "{{ ansible_env.HOME }}/dotfiles/configs/aerospace.toml", dest: "{{ ansible_env.HOME }}/.aerospace.toml" }
    - { src: "{{ ansible_env.HOME }}/dotfiles/configs/sketchybar", dest: "{{ ansible_env.HOME }}/.config/sketchybar" }
