# vim:ft=yaml.ansible
---
- name: Docker global docker-compose
  ansible.builtin.copy:
    src: "{{ role_path }}/files/docker-compose.yml"
    dest: "{{ ansible_env.HOME }}/Developer/Global/docker-compose.yml"
    mode: '755'
