# vim:ft=yaml.ansible
---
- name: Arch | Install Docker
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
    state: latest
  loop:
    - docker
    - docker-compose
    - docker-buildx
    - lazydocker

- name: Arch | Docker Group
  ansible.builtin.group:
    name: docker
    state: present

- name: Arch | Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: true

- name: Arch | Enable docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
