# vim:ft=yaml.ansible
---

- name: Darwin | Install git stuff
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - git-delta
    - lazygit

- name: Darwin | Create lazygit directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/lazygit"
    state: directory
    mode: '755'

- name: Darwin | Git Config
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "{{ ansible_env.HOME }}/dotfiles/configs/git-configs/gitconfig", dest: "{{ ansible_env.HOME }}/.gitconfig" }
    - { src: "{{ ansible_env.HOME }}/dotfiles/configs/git-configs/lazygit.yml", dest: "{{ ansible_env.HOME }}/.config/lazygit/config.yml" }
