# vim:ft=yaml.ansible
---
- name: Arch | Install Prototools Dependencies
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
    state: latest
  loop:
    - git
    - gzip
    - uznip
    - xz

- name: Arch | Proto stat
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.prototools"
  register: proto_status

- name: Arch | Install prototools
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://moonrepo.dev/install/proto.sh | bash -s -- --no-profile --yes
  when: proto_status.stat.exists
  changed_when: true

- name: Arch | Proto Config
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "prototools", dest: "{{ ansible_env.HOME }}/.prototools" }
