# vim:ft=yaml.ansible
---
- name: Ensure the destination directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Developer/Personal"
    state: directory
    mode: '755'

- name: Ensure SSH key is addded
  ansible.builtin.shell: |
    set -o pipefail
    ssh-add $HOME/.ssh/id_rsa
  changed_when: false

- name: Add Github server to known_hosts
  ansible.builtin.known_hosts:
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"

- name: Clone repos
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ ansible_env.HOME }}/Developer/Personal/{{ item.name }}"
    clone: true
    accept_hostkey: true
    key_file: "{{ ansible_env.HOME }}/.ssh/id_rsa"
  environment:
    GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa'
  loop:
    - { name: isur, repo: "git@github.com:Isur/isur.git" }
    - { name: turbo-template, repo: "git@github.com:Isur/turbo-template.git" }
    - { name: portfolio, repo: "git@github.com:Isur/portfolio.git" }
