# vim:ft=yaml.ansible
---
- name: Ensure the destination directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Developer/Personal"
    state: directory
    mode: '755'

- name: Clone repos
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ ansible_env.HOME }}/Developer/Personal/{{ item.name }}"
    clone: true
    accept_hostkey: true
    key_file: "{{ ansible_env.HOME }}/.ssh/id_rsa"
  loop:
    - { name: isur, repo: "git@github.com:Isur/isur.git" }
    - { name: turbo-template, repo: "git@github.com:Isur/turbo-template.git" }
    - { name: portfolio, repo: "git@github.com:Isur/portfolio.git" }
