# vim:ft=yaml.ansible
---
- name: Darwin | Install terminal apps
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - fzf
    - ripgrep
    - fd
    - btop
    - sshs
    - gnu-sed

- name: Darwin | Install iterm2
  community.general.homebrew_cask:
    name: iterm2
    state: present
    accept_external_apps: true
