# vim:ft=yaml.ansible
---
- name: Arch | Install terminal
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
    state: latest
  loop:
    - fzf
    - ripgrep
    - fd
    - btop
    - sshs
    - ghostty

- name: Arch | Ghostty config dir
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/ghostty/"
    state: directory
    mode: "0755"

- name: Arch | Ghostty Config
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "ghostty", dest: "{{ ansible_env.HOME }}/.config/ghostty/config" }
