# vim:ft=yaml.ansible
---
- name: Darwin | Install terminal
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - kitty
    - fzf
    - ripgrep
    - fd
    - btop
    - sshs
    - gnu-sed

- name: Darwin | Kitty Config
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "kitty", dest: "{{ ansible_env.HOME }}/.config/kitty" }
