# vim:ft=yaml.ansible
---
- name: Arch | Install terminal
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
    state: latest
  loop:
    - kitty
    - fzf
    - ripgrep
    - fd
    - btop
    - sshs

- name: Arch | Kitty Config
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "{{ ansible_env.HOME }}/dotfiles/configs/kitty", dest: "{{ ansible_env.HOME }}/.config/kitty" }
    - { src: "{{ ansible_env.HOME }}/dotfiles/configs/themes/btop/catppuccin.theme", dest: "{{ ansible_env.HOME }}/.config/btop/themes/catppuccin.theme" }
