# vim:ft=yaml.ansible
---
- name: Darwin | Install tmux
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - tmux

- name: Darwin | Tmux Config
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "tmux.conf", dest: "{{ ansible_env.HOME }}/.tmux.conf" }
