# vim:ft=yaml.ansible
---
- name: Create directories
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  with_items:
    - apps
    - .config
    - .local/bin
    - Developer
    - Developer/Clients
    - Developer/Personal
    - Developer/PoC
    - Developer/Global
    - Pictures/Screenshots
