# vim:ft=yaml.ansible
---
- name: Install Gaming Stuff
  become: true
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
    state: latest
  with_items:
    - wine
    - steam
    - lutris
    - nvidia-dkms
    - nvidia-utils
    - lib32-nvidia-utils
    - nvidia-settings
    - vulkan-icd-loader
    - lib32-vulkan-icd-loader
    - gamemode
    - lib32-gamemode
