[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "none"

[env]
TERM = "xterm-256color"

##### TokyoNight Alacritty Colors #####
# # Default colors
# [colors.primary]
# background = '#1a1b26'
# foreground = '#c0caf5'
#
# #[colors.cursor]
# #cursor = '#c0caf5'
# #text = '#1a1b26'
#
# Normal colors
# [colors.normal]
# black = '#15161e'
# red = '#f7768e'
# green = '#9ece6a'
# yellow = '#e0af68'
# blue = '#7aa2f7'
# magenta = '#bb9af7'
# cyan = '#7dcfff'
# white = '#a9b1d6'
#
# # Bright colors
# [colors.bright]
# black = '#414868'
# red = '#f7768e'
# green = '#9ece6a'
# yellow = '#e0af68'
# blue = '#7aa2f7'
# magenta = '#bb9af7'
# cyan = '#7dcfff'
# white = '#c0caf5'
#
# # Indexed Colors
# [[colors.indexed_colors]]
# index = 16
# color = '#ff9e64'
#
# [[colors.indexed_colors]]
# index = 17
# color = '#db4b4b'

##### GRUVBOX #####
# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
