#!/usr/bin/env bash

cryptomator-cli unlock \
    --password:stdin \
    --mounter=org.cryptomator.frontend.fuse.mount.LinuxFuseMountProvider \
    --mountPoint=$HOME/data_vault/secret_data_open \
    $HOME/data_vault/secret_data/


