#!/usr/bin/env bash

win="no"
if [[ $1 == '--win' ]]; then
    win="yes"
fi

selected_name=$(tmux list-sessions -F "#S" | fzf)

if [[ $win == "no" ]]; then
    tmux switch-client -t $selected_name
else
    window_name=$(tmux list-windows -t $selected_name -F "#S #I #W" | fzf)

    echo $window_name

    s=$(echo $window_name | awk '{ session = $1 }; END { print session }')
    w=$(echo $window_name | awk '{ window = $2 }; END { print window }')

    change=$s:$w

    tmux switch-client -t $change
fi
