#!/usr/bin/env bash

win="no"
if [[ $1 == '--win' ]]; then
    win="yes"
fi


if [[ $win == "no" ]]; then
    window_name=$(tmux list-windows -a -F "#I #S #W" | fzf)

    s=$(echo $window_name | awk '{ session = $2 }; END { print session }')
    w=$(echo $window_name | awk '{ window = $3 }; END { print window }')
    i=$(echo $window_name | awk '{ id = $1 }; END { print id }')

    change=$s:$i

    tmux switch-client -t $change
else
    selected_name=$(tmux list-windows -F "#S:#W" | fzf)
    tmux switch-client -t $selected_name
fi
