#!/usr/bin/env bash

win="no"
if [[ $1 == '--win' ]]; then
    win="yes"
fi


if [[ $win == "no" ]]; then
    window_name=$(tmux list-windows -a -F "#S #W" | fzf)

    s=$(echo $window_name | awk '{ session = $1 }; END { print session }')
    w=$(echo $window_name | awk '{ window = $2 }; END { print window }')

    change=$s:$w

    tmux switch-client -t $change
else
    selected_name=$(tmux list-windows -F "#S:#W" | fzf)
    tmux switch-client -t $selected_name
fi
