#!/usr/bin/env bash

WALLPAPER_DIR="$HOME/dotfiles/wallpapers"
FOCUSED_MONITOR="DP-1"

replace() {
    CURRENT_WALL=$(hyprctl hyprpaper listloaded)
    WALLPAPER=$(find "$1" -type f ! -name "$(basename "$CURRENT_WALL")" | shuf -n 1)
    hyprctl hyprpaper wallpaper "$2, $WALLPAPER"
}

case "$1" in
    wide)
        replace "$HOME/dotfiles/wallpapers/Wide" "DP-2"
        ;;
    1080)
        replace "$HOME/dotfiles/wallpapers/1080p" "DP-1"
        ;;
    *)
        replace "$HOME/dotfiles/wallpapers/1080p" "DP-1"
        replace "$HOME/dotfiles/wallpapers/Wide" "DP-2"
        ;;
esac



