# vim:ft=yaml.ansible
---
- name: Arch | Upgrade System
  become: true
  kewlfft.aur.aur:
    upgrade: true
    use: yay

- name: Arch | Install some packages and apps
  become: true
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
    state: latest
  loop:
    - yay
    - sysstat
    - gvfs
    - font-awesome-5
    - ttf-jetbrains-mono-nerd
    - ttf-maple
    - mpv
    - bazecor
    - thunderbird
    - thunderbird-i18n
    - spotify-launcher
    - obsidian
    - discord
    - zen-browser-bin
    - thunar
    - flameshot
