# vim:ft=yaml.ansible
---
- name: Create Linux directories
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
    mode: '755'
  loop:
    - apps
    - Pictures/Screenshots
