# vim:ft=yaml.ansible
---
- name: Arch | Prep modfile
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/modprobe.d/nvidia.conf
    regexp: '^options\s+nvidia_drm\s+modeset='
    line: 'options nvidia_drm modeset=1'
    create: true
    mode: '0644'

- name: Arch | Config hyprland
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - { src: "hyprland", dest: "{{ ansible_facts['env']['HOME'] }}/.config/hypr" }
    - { src: "mako", dest: "{{ ansible_facts['env']['HOME'] }}/.config/mako" }
    - { src: "rofi", dest: "{{ ansible_facts['env']['HOME'] }}/.config/rofi" }
    - { src: "waybar", dest: "{{ ansible_facts['env']['HOME'] }}/.config/waybar" }

- name: Arch | Waybar theme.css
  ansible.builtin.copy:
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/waybar/theme.css"
    mode: "0644"
    content: ""
    force: false
    group: "{{ ansible_facts['user_id'] }}"
    owner: "{{ ansible_facts['user_id'] }}"

- name: Arch | Enable SDDM
  become: true
  ansible.builtin.systemd:
    name: "{{ item}}"
    enabled: true
  loop:
    - "sddm"
    - "bluetooth"
