# vim:ft=yaml.ansible
---
- name: Common general tasks
  ansible.builtin.include_tasks: "./{{ task }}"
  loop:
    - dev.yml
    - repos.yml
  loop_control:
    loop_var: task

- name: Darwin | Include Darwin specific tasks
  ansible.builtin.include_tasks: "./{{ task }}"
  when: ansible_os_family == 'Darwin'
  loop:
    - dev.darwin.yml
  loop_control:
    loop_var: task

- name: Arch | Include Linux specific tasks
  ansible.builtin.include_tasks: "./{{ task }}"
  when: ansible_os_family == 'Archlinux'
  loop:
    - hyprland.arch.yml
    - dev.arch.yml
  loop_control:
    loop_var: task
