# https://nikitabobko.github.io/AeroSpace/guide

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

after-startup-command = [
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=8.0',
  'exec-and-forget sketchybar'
]

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

[gaps]
inner.horizontal = 16
inner.vertical =   16
outer.left =       8
outer.bottom =     48
outer.top =        8
outer.right =      8

[mode.main.binding]
ctrl-alt-h = 'focus --boundaries-action stop --boundaries all-monitors-outer-frame left'
ctrl-alt-j = 'focus --boundaries-action stop --boundaries all-monitors-outer-frame down'
ctrl-alt-k = 'focus --boundaries-action stop --boundaries all-monitors-outer-frame up'
ctrl-alt-l = 'focus --boundaries-action stop --boundaries all-monitors-outer-frame right'

ctrl-alt-shift-h = 'move left'
ctrl-alt-shift-j = 'move down'
ctrl-alt-shift-k = 'move up'
ctrl-alt-shift-l = 'move right'

ctrl-alt-shift-a = ['join-with left', 'mode main']
ctrl-alt-shift-s = ['join-with down', 'mode main']
ctrl-alt-shift-d = ['join-with up', 'mode main']
ctrl-alt-shift-f = ['join-with right', 'mode main']

ctrl-alt-f = 'fullscreen'

ctrl-alt-s = 'layout v_accordion'
ctrl-alt-w = 'layout h_accordion'
ctrl-alt-e = 'layout tiles horizontal vertical'

ctrl-alt-t = 'layout floating tiling'

ctrl-alt-1 = 'workspace 1'
ctrl-alt-2 = 'workspace 2'
ctrl-alt-3 = 'workspace 3'
ctrl-alt-4 = 'workspace 4'
ctrl-alt-5 = 'workspace 5'
ctrl-alt-6 = 'workspace 6'
ctrl-alt-7 = 'workspace 7'
ctrl-alt-8 = 'workspace 8'
ctrl-alt-9 = 'workspace 9'
ctrl-alt-0 = 'workspace 10'

ctrl-alt-shift-1 = 'move-node-to-workspace 1'
ctrl-alt-shift-2 = 'move-node-to-workspace 2'
ctrl-alt-shift-3 = 'move-node-to-workspace 3'
ctrl-alt-shift-4 = 'move-node-to-workspace 4'
ctrl-alt-shift-5 = 'move-node-to-workspace 5'
ctrl-alt-shift-6 = 'move-node-to-workspace 6'
ctrl-alt-shift-7 = 'move-node-to-workspace 7'
ctrl-alt-shift-8 = 'move-node-to-workspace 8'
ctrl-alt-shift-9 = 'move-node-to-workspace 9'
ctrl-alt-shift-0 = 'move-node-to-workspace 10'

ctrl-alt-shift-r = 'reload-config'

ctrl-alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
b = 'balance-sizes'
enter = 'mode main'
esc = 'mode main'

[workspace-to-monitor-force-assignment]
1 = 1
2 = 1
3 = 1
4 = 1
5 = 1
6 = 1
7 = 1
8 = 1
9 = 2
10 = 2

[[on-window-detected]]
if.app-id = 'cc.ffitch.shottr'
run = ['layout floating']
