# vim:ft=yaml.ansible
---
- name: Update dotfiles
  ansible.builtin.git:
    repo: "git@github.com:Isur/dotfiles.git"
    dest: "{{ ansible_env.HOME }}/dotfiles"
    update: true
    clone: false
  register: dotfiles_update_result

- name: Show dotfiles update output
  ansible.builtin.debug:
    var: dotfiles_update_result.stdout_lines
