# vim:ft=yaml.ansible
---
- name: Update dotfiles
  ansible.builtin.shell: |
    set -o pipefail
    git pull
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}/dotfiles"
  register: dotfiles_update_result
  changed_when: "'Already up to date' not in dotfiles_update_result.stdout"
