# vim:ft=yaml.ansible
---
- name: Darwin | Include Darwin specific tasks
  ansible.builtin.include_tasks: "./{{ task }}"
  when: ansible_os_family == 'Darwin'
  loop:
    - update.darwin.yml
    - omz.yml
    - dotfiles.yml
  loop_control:
    loop_var: task

- name: Arch | Include Linux specific tasks
  ansible.builtin.include_tasks: "./{{ task }}"
  when: ansible_os_family == 'Archlinux'
  loop:
    - update.arch.yml
    - omz.yml
    - dotfiles.yml
  loop_control:
    loop_var: task
