# vim:ft=yaml.ansible
---
- name: Darwin | Upgrade Homebrew formulae
  ansible.builtin.shell: |
    set -o pipefail
    brew update && brew upgrade
  register: brew_upgrade
  changed_when: "'Already up-to-date' not in brew_upgrade.stdout and 'No outdated packages' not in brew_upgrade.stdout"

- name: Darwin | Upgrade Homebrew casks
  ansible.builtin.shell: |
    set -o pipefail
    brew upgrade --cask
  register: brew_cask_upgrade
  changed_when: "'No cask upgrades' not in brew_cask_upgrade.stdout"
