# vim:ft=yaml.ansible
---
- name: Arch | Upgrade System
  ansible.builtin.shell: |
    set -o pipefail
    yay -Syu --noconfirm
  register: yay_upgrade
  changed_when: "'there is nothing to do' not in yay_upgrade.stdout"
