# vim:ft=yaml.ansible
---

- name: Arch | Install AUR dev apps with no config
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
    state: latest
  loop:
    - dbeaver
    - postman-bin
    - virtualbox
