config-version = 2
start-at-login = false

persistent-workspaces = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]

[workspace-to-monitor-force-assignment]
1 = 'secondary' # ghostty/terminal
2 = 'secondary' # browser
3 = 'secondary' # database
4 = 'main'      # notes
5 = 'main'      # browser 2
6 = 'main'      #
7 = 'main'      # mail
8 = 'main'      # Spotify
9 = 'main'      # Slack / communicator
10 = 'secondary'#

[mode.main.binding]
cmd-e = 'exec-and-forget open -a Finder'
cmd-d = 'exec-and-forget open -a Raycast'

cmd-q = 'close'
cmd-f = 'fullscreen'
cmd-space = 'layout floating tiling'

cmd-h = 'focus left'
cmd-j = 'focus down'
cmd-k = 'focus up'
cmd-l = 'focus right'

cmd-shift-h = 'move left'
cmd-shift-j = 'move down'
cmd-shift-k = 'move up'
cmd-shift-l = 'move right'

cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'
cmd-0 = 'workspace 10'

cmd-shift-1 = 'move-node-to-workspace 1'
cmd-shift-2 = 'move-node-to-workspace 2'
cmd-shift-3 = 'move-node-to-workspace 3'
cmd-shift-4 = 'move-node-to-workspace 4'
cmd-shift-5 = 'move-node-to-workspace 5'
cmd-shift-6 = 'move-node-to-workspace 6'
cmd-shift-7 = 'move-node-to-workspace 7'
cmd-shift-8 = 'move-node-to-workspace 8'
cmd-shift-9 = 'move-node-to-workspace 9'
cmd-shift-0 = 'move-node-to-workspace 10'


[[on-window-detected]]
if.app-name-regex-substring = 'dbeaver'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-name-regex-substring = 'obsidian'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-name-regex-substring = 'mail'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-name-regex-substring = 'spotify'
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-id = 'cc.ffitch.shottr'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'slack'
run = 'move-node-to-workspace 9'
