config-version = 2
start-at-login = false
persistent-workspaces = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]

[gaps]
outer.top = [{ monitor."built-in" = 0 }, 32]


[workspace-to-monitor-force-assignment]
1 = 'secondary' # ghostty/terminal
2 = 'secondary' # browser
3 = 'secondary' # database
4 = 'main'      # notes
5 = 'main'      # browser 2
6 = 'main'      #
7 = 'main'      # mail
8 = 'main'      # Spotify
9 = 'main'      # Slack / communicator
10 = 'secondary'#

[mode.main.binding]
cmd-alt-ctrl-enter = 'exec-and-forget open -a Ghostty'
cmd-alt-ctrl-e = 'exec-and-forget open -a Finder'
cmd-alt-ctrl-d = 'exec-and-forget open -a Raycast'

cmd-alt-ctrl-q = 'close'
cmd-alt-ctrl-f = 'fullscreen'
cmd-alt-ctrl-space = 'layout floating tiling'

cmd-alt-ctrl-h = 'focus left'
cmd-alt-ctrl-j = 'focus down'
cmd-alt-ctrl-k = 'focus up'
cmd-alt-ctrl-l = 'focus right'

cmd-alt-ctrl-shift-h = 'move left'
cmd-alt-ctrl-shift-j = 'move down'
cmd-alt-ctrl-shift-k = 'move up'
cmd-alt-ctrl-shift-l = 'move right'

cmd-alt-ctrl-shift-1 = 'move-node-to-workspace 1'
cmd-alt-ctrl-shift-2 = 'move-node-to-workspace 2'
cmd-alt-ctrl-shift-3 = 'move-node-to-workspace 3'
cmd-alt-ctrl-shift-4 = 'move-node-to-workspace 4'
cmd-alt-ctrl-shift-5 = 'move-node-to-workspace 5'
cmd-alt-ctrl-shift-6 = 'move-node-to-workspace 6'
cmd-alt-ctrl-shift-7 = 'move-node-to-workspace 7'
cmd-alt-ctrl-shift-8 = 'move-node-to-workspace 8'
cmd-alt-ctrl-shift-9 = 'move-node-to-workspace 9'
cmd-alt-ctrl-shift-0 = 'move-node-to-workspace 10'

cmd-alt-ctrl-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'

esc = 'mode main'


[[on-window-detected]]
if.app-name-regex-substring = 'dbeaver'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-name-regex-substring = 'obsidian'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-name-regex-substring = 'mail'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-name-regex-substring = 'spotify'
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-id = 'cc.ffitch.shottr'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'slack'
run = 'move-node-to-workspace 9'
